baseURL = "https://nkollmann.netlify.app/"
languageCode = "en-us"
title = "Nicola Kollmann Data Portfolio & Blog"
theme = "data-science"
disqusShortname = "nicolakollmann"
enableEmoji = true
# allow search engines to search/crawl everything
enableRobotsTXT = true

preserveTaxonomyNames = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]

# sectionPagesMenu = "main"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  author = "Nicola Kollmann"
  description = "A collection of my data science projects and blog posts about R."
  twitterAuthor = "@NicolaKollmann"
  twitterSite = "@NicolaKollmann"
  images = ['profile.jpeg']

  # options for highlight.js (version, additional languages, and theme)
  highlight = true
  highlightjsVersion = "9.15.6"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "javascript"]
  custom = true
  highlightjsThemeLight = ""
  highlightjsThemeDark = ""




[params.social]
  email = "mailto:nicola@kollmann.li"
  twitter = "https://twitter.com/NicolaKollmann"
  github = "https://www.github.com/NicolaKollmann"
  linkedin = "https://www.linkedin.com/in/nicolakollmann/"
  stackoverflow = ""
  facebook = ""
  instagram = "https://www.instagram.com/nicolakollmann/"
  dribbble = ""
  kaggle = ""
  medium = ""
  patreon = ""
  pinterest = ""
  youtube = ""
